name: hSRCom
version: 0.1.0.0
github: "githubuser/hSRCom"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hSRCom#readme>

dependencies:
  - base >= 4.7 && < 5
  - wreq
  - bytestring
  - text
  - strict
  - lens
  - aeson

library:
  default-extensions:
    - OverloadedStrings
  source-dirs: src

executables:
  hSRCom-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hSRCom

tests:
  hSRCom-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hSRCom
